version: "3"

services:
  mysql:
    image: mysql:8.0.26
    container_name: db_mysql
    restart: always
    environment:
    - MYSQL_ROOT_PASSWORD=Unu#2023
    ports:
    - 3309:3306
    - 33063:33060
    networks:
    - Proyecto 
networks:
  Proyecto:
    name: ms-proyecto
